export type Side = "long" | "short";
export type TP = { movePct: number | null; closePct: number | null };
export type InstrumentMetadata = { symbol?: string; tickSize: number | null; qtyStep: number | null; minOrderQty: number | null; minNotionalValue: number | null };
export type PositionState = { side: Side; size: number | null; avgEntryPrice: number | null; unrealizedPnl: number | null; leverage: number | null; initialMargin: number | null; maintenanceMargin: number | null; notional: number | null };
export type ExchangeOrder = { orderId: string | null; side: string | null; status: string | null; price: number | null; qty: number | null; leavesQty: number | null };
export type GridOrder = { id: string; side: Side; level: number; offsetPct: number | null; qty: number | null; filledQty: number; avgFill: number | null; tps: TP[]; note: string };
export type PositionMode = "HEDGE" | "ONE_WAY" | "UNKNOWN";
export type AccountState = { symbol: string; positionMode: PositionMode; positionModeSymbol: string | null; markPrice: number | null; availableMargin: number | null; equity: number | null; walletBalance: number | null; initialMargin: number | null; maintenanceMargin: number | null; grossExposure: number | null; netExposure: number | null; longPosition: PositionState | null; shortPosition: PositionState | null; openOrders: ExchangeOrder[]; ordersAvailable: boolean; ordersError: string | null; instrument: InstrumentMetadata | null; updatedAt: string | null; source: string; stale: boolean; error?: string };
export type Allocation = { longPct: number | null; shortPct: number | null; reservePct: number | null };
export const initialAccount: AccountState = { symbol: "BTCUSDT", positionMode: "UNKNOWN", positionModeSymbol: null, markPrice: null, availableMargin: null, equity: null, walletBalance: null, initialMargin: null, maintenanceMargin: null, grossExposure: null, netExposure: null, longPosition: null, shortPosition: null, openOrders: [], ordersAvailable: false, ordersError: null, instrument: null, updatedAt: null, source: "нет соединения", stale: true };
export const uid = () => Math.random().toString(36).slice(2, 10);
export function newOrder(side: Side, level: number): GridOrder { return { id: uid(), side, level, offsetPct: null, qty: null, filledQty: 0, avgFill: null, tps: [], note: "" }; }
export function round(value: number, tickSize: number | null): number { return tickSize && tickSize > 0 ? Math.round(value / tickSize) * tickSize : value; }
export function prices(mark: number | null, side: Side, orders: GridOrder[], tickSize: number | null): (number | null)[] { if (mark == null) return orders.map(() => null); let previous = mark; return orders.map((o) => { if (o.offsetPct == null) return null; previous = round(previous * (side === "long" ? 1 - o.offsetPct / 100 : 1 + o.offsetPct / 100), tickSize); return previous; }); }
export function allocationLimits(account: AccountState, allocation: Allocation) { return { long: account.availableMargin != null && allocation.longPct != null ? account.availableMargin * allocation.longPct / 100 : null, short: account.availableMargin != null && allocation.shortPct != null ? account.availableMargin * allocation.shortPct / 100 : null, reserve: account.availableMargin != null && allocation.reservePct != null ? account.availableMargin * allocation.reservePct / 100 : null }; }
export function margin(order: GridOrder, price: number | null, leverage: number | null): number | null { return price != null && order.qty != null && leverage != null && leverage > 0 ? price * order.qty / leverage : null; }
export function tpPrice(order: GridOrder, price: number | null, tp: TP, tickSize: number | null): number | null { return price == null || tp.movePct == null ? null : round(price * (order.side === "long" ? 1 + tp.movePct / 100 : 1 - tp.movePct / 100), tickSize); }
export function pnl(order: GridOrder, entry: number | null, tp: TP, tickSize: number | null): number | null { const exit = tpPrice(order, entry, tp, tickSize); const baseQty = order.filledQty > 0 ? order.filledQty : order.qty; return entry != null && exit != null && baseQty != null && tp.closePct != null ? (exit - entry) * baseQty * (order.side === "long" ? 1 : -1) * tp.closePct / 100 : null; }
export function guard(account: AccountState, allocation: Allocation, side: Side, orders: GridOrder[], tickSize: number | null, leverage: number | null) { const limit = allocationLimits(account, allocation)[side]; const plannedValues = prices(account.markPrice, side, orders, tickSize).map((price, i) => margin(orders[i], price, leverage)); const planned = plannedValues.length > 0 && plannedValues.every((value) => value != null) ? plannedValues.reduce<number>((sum, value) => sum + (value ?? 0), 0) : null; return { limit, planned, remaining: limit != null && planned != null ? limit - planned : null, allowed: limit != null && planned != null && planned <= limit }; }
