import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, ArrowDown, ArrowUp, Check, ChevronDown, Clock3, History, LockKeyhole, Plus, Save, Settings2, ShieldCheck, Trash2, Wifi, X } from "lucide-react";
import { AccountState, Allocation, GridOrder, Side, allocationLimits, guard, initialAccount, limits, newOrder, pnl, prices, tpPrice } from "./domain";
import "./styles.css";

const money = (n: number, digits = 2) => `${n.toLocaleString("ru-RU", { minimumFractionDigits: digits, maximumFractionDigits: digits })} USDT`;
const qty = (n: number) => n.toLocaleString("ru-RU", { maximumFractionDigits: 4 });
const pct = (n: number) => `${n.toLocaleString("ru-RU", { maximumFractionDigits: 2 })}%`;

function App() {
  const [account, setAccount] = useState(initialAccount);
  const [allocation, setAllocation] = useState<Allocation>({ longPct: 40, shortPct: 20, reservePct: 40 });
  const [long, setLong] = useState<GridOrder[]>([1, 2, 3, 4].map((n) => newOrder("long", n)));
  const [short, setShort] = useState<GridOrder[]>([1, 2, 3, 4].map((n) => newOrder("short", n)));
  const [activeLong, setActiveLong] = useState(2); const [activeShort, setActiveShort] = useState(2);
  const [revisions, setRevisions] = useState<{time: string; action: string; side?: string}[]>([]);
  const [notice, setNotice] = useState("");
  const [historyOpen, setHistoryOpen] = useState(false); const [saving, setSaving] = useState(false);
  const available = account.availableMargin;
  const limitsBySide = allocationLimits(account, allocation);
  const longGuard = guard(account, allocation, "long", long); const shortGuard = guard(account, allocation, "short", short);
  const totalPlanned = longGuard.planned + shortGuard.planned;
  const updateAccount = (field: keyof AccountState, value: string) => setAccount((a) => ({ ...a, [field]: Number(value) }));
  const updateAllocation = (key: keyof Allocation, value: string) => setAllocation((a) => ({ ...a, [key]: Number(value) }));
  const editOrder = (side: Side, id: string, patch: Partial<GridOrder>) => { const setter = side === "long" ? setLong : setShort; setter((items) => items.map((o) => o.id === id ? { ...o, ...patch } : o)); };
  const addOrder = (side: Side) => { const setter = side === "long" ? setLong : setShort; setter((items) => [...items, newOrder(side, items.length + 1)]); };
  const removeOrder = (side: Side, id: string) => { const setter = side === "long" ? setLong : setShort; setter((items) => items.filter((o) => o.id !== id).map((o, i) => ({ ...o, level: i + 1 }))); };
  const save = async () => {
    setSaving(true); setNotice("");
    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || "http://localhost:8000"}/api/revisions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol: account.symbol, comment: "", payload: { allocation, activeLong, activeShort, long, short, market_snapshot: account } }) });
      if (!response.ok) throw new Error("save failed");
      setRevisions((r) => [{ time: new Date().toLocaleString("ru-RU"), action: "Сохранена новая версия конфигурации" }, ...r]);
      setNotice("Версия сохранена в PostgreSQL");
    } catch { setNotice("Не удалось сохранить: проверьте backend и PostgreSQL"); }
    setSaving(false);
  };
  const planBlocked = !longGuard.allowed || !shortGuard.allowed || allocation.longPct + allocation.shortPct + allocation.reservePct !== 100;
  useEffect(() => {
    const load = async () => {
      try {
        const response = await fetch(`${import.meta.env.VITE_API_URL || "http://localhost:8000"}/api/state/${account.symbol}`);
        if (!response.ok) return;
        const data = await response.json();
        if (data.source === "bybit_read_only") setAccount((a) => ({ ...a, markPrice: Number(data.mark_price || a.markPrice), availableMargin: Number(data.available_margin || a.availableMargin), equity: Number(data.equity || a.equity), walletBalance: Number(data.wallet_balance || a.walletBalance), initialMargin: Number(data.initial_margin || a.initialMargin), maintenanceMargin: Number(data.maintenance_margin || a.maintenanceMargin), source: data.source, updatedAt: new Date().toISOString() }));
      } catch { /* demo state remains visible when backend is offline */ }
    };
    void load();
    const timer = setInterval(load, 15000);
    return () => clearInterval(timer);
  }, [account.symbol]);
  return <div className="app-shell">
    <aside className="sidebar"><div className="logo"><span>G</span><div>GRID<br/><b>CONTROL</b></div></div><div className="mode-pill"><span></span> ТЕСТОВЫЙ РЕЖИМ</div><nav><button className="active"><Settings2 size={16}/> Конструктор</button><button><Activity size={16}/> Состояние</button><button onClick={() => setHistoryOpen(true)}><History size={16}/> История</button></nav><div className="sidebar-bottom"><LockKeyhole size={15}/><span>Только чтение<br/><small>Bybit write API отключён</small></span></div></aside>
    <main className="content"><header className="topbar"><div><div className="crumb">MANUAL GRID / CONFIGURATION</div><h1>Ручная настройка сетки</h1>{notice && <div className="notice">{notice}</div>}</div><div className="top-actions"><span className="connection"><Wifi size={14}/> {account.source === "demo" ? "Демо-данные" : "Bybit read-only"}</span><button className="outline" onClick={() => setHistoryOpen(true)}><History size={16}/> История</button><button className="save" onClick={save}><Save size={16}/> {saving ? "Сохраняю…" : "Сохранить версию"}</button></div></header>
      <section className="account-strip"><div className="symbol-select"><span>ИНСТРУМЕНТ</span><b>{account.symbol}</b><ChevronDown size={14}/></div><Metric label="Mark Price" value={account.markPrice.toFixed(4)}/><Metric label="Баланс кошелька" value={money(account.walletBalance)}/><Metric label="Equity" value={money(account.equity)}/><Metric label="Доступная маржа" value={money(available)} accent/><div className="updated"><Clock3 size={13}/> {new Date(account.updatedAt).toLocaleTimeString("ru-RU")}</div></section>
      <section className="allocation-panel"><div className="section-title"><div><span className="overline">КАПИТАЛ</span><h2>Распределение доступной маржи</h2></div><span className="allocation-total">{allocation.longPct + allocation.shortPct + allocation.reservePct === 100 ? <><Check size={14}/> 100% распределено</> : <><X size={14}/> Должно быть 100%</>}</span></div><div className="allocation-grid"><AllocationBox title="Long" color="green" value={allocation.longPct} limit={limitsBySide.long} onChange={(v) => updateAllocation("longPct", v)}/><AllocationBox title="Short" color="red" value={allocation.shortPct} limit={limitsBySide.short} onChange={(v) => updateAllocation("shortPct", v)}/><AllocationBox title="Резерв" color="amber" value={allocation.reservePct} limit={limitsBySide.reserve} onChange={(v) => updateAllocation("reservePct", v)}/></div></section>
      <div className="three-columns"><GridColumn side="long" orders={long} active={activeLong} mark={account.markPrice} guard={longGuard} onActive={setActiveLong} onAdd={() => addOrder("long")} onEdit={(id, p) => editOrder("long", id, p)} onRemove={(id) => removeOrder("long", id)}/><CenterPanel account={account} long={long} short={short} totalPlanned={totalPlanned} blocked={planBlocked}/><GridColumn side="short" orders={short} active={activeShort} mark={account.markPrice} guard={shortGuard} onActive={setActiveShort} onAdd={() => addOrder("short")} onEdit={(id, p) => editOrder("short", id, p)} onRemove={(id) => removeOrder("short", id)}/></div>
    </main>{historyOpen && <HistoryDrawer items={revisions} close={() => setHistoryOpen(false)}/>} 
  </div>;
}

function Metric({label, value, accent}: {label:string;value:string;accent?:boolean}) { return <div className={`metric ${accent ? "accent" : ""}`}><span>{label}</span><b>{value}</b></div>; }
function AllocationBox({title,color,value,limit,onChange}:{title:string;color:string;value:number;limit:number;onChange:(v:string)=>void}) { return <div className="allocation-box"><div className="alloc-head"><span className={`dot ${color}`}></span><b>{title}</b><label><input type="number" value={value} onChange={(e) => onChange(e.target.value)}/> %</label></div><div className="gauge"><div className={`gauge-fill ${color}`} style={{width:`${Math.min(value,100)}%`}}></div></div><div className="alloc-foot"><span>Лимит</span><strong>{money(limit)}</strong></div></div>; }

function GridColumn({side,orders,active,mark,guard: check,onActive,onAdd,onEdit,onRemove}:{side:Side;orders:GridOrder[];active:number;mark:number;guard:{limit:number;planned:number;remaining:number;allowed:boolean};onActive:(v:number)=>void;onAdd:()=>void;onEdit:(id:string,p:Partial<GridOrder>)=>void;onRemove:(id:string)=>void}) { const ps = prices(mark, side, orders); return <section className={`grid-column ${side}`}><div className="grid-head"><div><div className="side-label"><span className="side-icon">{side === "long" ? <ArrowDown size={15}/> : <ArrowUp size={15}/>}</span><span>{side === "long" ? "LONG GRID" : "SHORT GRID"}</span></div><h2>{orders.length} уровней</h2></div><button className="icon-button" onClick={onAdd}><Plus size={17}/></button></div><div className="grid-summary"><span>Плановая маржа</span><b className={check.allowed ? "" : "danger"}>{money(check.planned)}</b><small>из {money(check.limit)}</small></div><div className="window-control"><span>Активное окно</span><input type="number" min="1" max={orders.length} value={active} onChange={(e) => onActive(Number(e.target.value))}/><span>уровня</span></div><div className="order-list">{orders.map((order, i) => <OrderCard key={order.id} order={order} price={ps[i]} active={i < active} onEdit={(p) => onEdit(order.id, p)} onRemove={() => onRemove(order.id)}/>)}</div><button className="add-order" onClick={onAdd}><Plus size={15}/> Добавить уровень</button></section>; }

function OrderCard({order,price,active,onEdit,onRemove}:{order:GridOrder;price:number;active:boolean;onEdit:(p:Partial<GridOrder>)=>void;onRemove:()=>void}) { const [expanded,setExpanded] = useState(true); return <article className={`order-card ${active ? "active" : "queued"}`}><div className="order-top"><span className="level">#{order.level}</span><span className={`order-status ${active ? "green" : "gray"}`}>{active ? "Активен" : "В очереди"}</span><button className="collapse" onClick={() => setExpanded(!expanded)}>{expanded ? "Свернуть" : "Развернуть"}</button><button className="delete" onClick={onRemove}><Trash2 size={14}/></button></div><div className="price-row"><div><span>Цена входа</span><b>{price.toFixed(4)}</b></div><div><span>{order.level === 1 ? "Отступ от текущей цены" : "Отступ от предыдущего"}</span><label><input type="number" value={order.offsetPct} step="0.1" onChange={(e) => onEdit({offsetPct:Number(e.target.value)})}/> %</label></div></div>{expanded && <><div className="order-inputs"><label>Объём, монет<input type="number" value={order.qty} onChange={(e) => onEdit({qty:Number(e.target.value)})}/></label><div><span>Плановая маржа</span><b>{money(price * order.qty / limits.leverage)}</b></div><div><span>Исполнено</span><b>{qty(order.filledQty)} / {qty(order.qty)}</b></div></div><div className="tp-section"><div className="tp-title"><b>Take Profit</b><span>План · от цены входа</span><button onClick={() => onEdit({tps:[...order.tps,{movePct:3,closePct:25}]})}><Plus size={13}/> TP</button></div>{order.tps.map((tp,i) => <div className="tp-line" key={i}><span>TP {i+1}</span><input type="number" value={tp.movePct} onChange={(e) => { const t=[...order.tps]; t[i]={...t[i],movePct:Number(e.target.value)}; onEdit({tps:t}); }}/><span>% →</span><input type="number" value={tp.closePct} onChange={(e) => { const t=[...order.tps]; t[i]={...t[i],closePct:Number(e.target.value)}; onEdit({tps:t}); }}/><span>% объёма</span><b>{tpPrice(order, price, tp).toFixed(4)}</b><em>{money(pnl(order,price,tp))}</em></div>)}</div><input className="note" placeholder="Заметка к ордеру..." value={order.note} onChange={(e) => onEdit({note:e.target.value})}/></>}</article>; }

function CenterPanel({account,long,short,totalPlanned,blocked}:{account:AccountState;long:GridOrder[];short:GridOrder[];totalPlanned:number;blocked:boolean}) { const lp=prices(account.markPrice,"long",long), sp=prices(account.markPrice,"short",short); return <section className="center-panel"><div className="center-heading"><span className="overline">ОБЩИЙ РАСЧЁТ</span><h2>Состояние стратегии</h2></div><div className="position-box"><div className="position-head"><span>Текущая позиция</span><span className="demo-tag">ДЕМО</span></div><div className="position-values"><div><span>Long avg</span><b>—</b></div><div><span>Short avg</span><b>—</b></div><div><span>Net exposure</span><b>0.00</b></div></div></div><div className="ladder"><div className="ladder-title">Лестница цен</div>{sp.slice().reverse().map((p,i)=><div className="rung short-rung" key={`s${i}`}><span>SHORT #{sp.length-i}</span><b>{p.toFixed(4)}</b></div>)}<div className="mark-line"><i></i><span>Mark Price</span><b>{account.markPrice.toFixed(4)}</b></div>{lp.map((p,i)=><div className="rung long-rung" key={`l${i}`}><span>LONG #{i+1}</span><b>{p.toFixed(4)}</b></div>)}</div><div className="plan-box"><div><span>Плановая маржа</span><b>{money(totalPlanned)}</b></div><div><span>Плановый P&L</span><b>—</b></div><div><span>Оценка комиссий</span><b>—</b></div></div><div className={`guard ${blocked ? "blocked" : "ok"}`}>{blocked ? <X size={16}/> : <ShieldCheck size={16}/>}<div><b>{blocked ? "Подготовка заблокирована" : "Конфигурация допустима"}</b><small>{blocked ? "Проверьте allocation и полную маржу сетки" : "Сетка не превышает выделенный лимит"}</small></div></div></section>; }
function HistoryDrawer({items,close}:{items:{time:string;action:string}[];close:()=>void}) { return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><span className="overline">AUDIT LOG</span><h2>История изменений</h2></div><button onClick={close}><X size={18}/></button></div>{items.length === 0 ? <div className="empty">Изменений пока нет.<br/><small>Сохраните первую версию конфигурации.</small></div> : items.map((x,i)=><div className="audit" key={i}><Check size={15}/><div><b>{x.action}</b><span>{x.time}</span></div></div>)}</aside></div>; }
createRoot(document.getElementById("root")!).render(<App />);
