import { AccountState } from "./domain";

export type HealthResponse = { status: string; private_integration: boolean; read_only: boolean; environment: "mainnet" | "testnet"; credential_source: string; account_state_ready: boolean; orders_ready: boolean; private_state_ready: boolean };
export type BybitDiagnosticsResponse = HealthResponse & { repository_root_found?: boolean; root_env_found?: boolean; module_env_found?: boolean; api_key_present: boolean; api_secret_present: boolean; query_api_status: string; wallet_status: string; positions_status: string; open_orders_status: string; last_safe_error: string | null };
export type TPCalculationResult = { price: string | number; qty: string | number; close_pct: string | number; gross_pnl: string | number; fee: string | number | null; net_pnl: string | number | null; basis: "planned_entry" | "actual_fill" };
export type OrderCalculationResult = { level: number; planned_entry_price: string | number; configured_qty: string | number; notional: string | number; planned_margin: string | number | null; cumulative_planned_average: string | number | null; planned_tp_qty: string | number; planned_remaining_after_all_tp: string | number; tp_steps: TPCalculationResult[]; validation_errors: Array<{ level: number; errors: string[] }>; status: "VALID" | "BLOCKED" };
export type SideCalculationResult = { side: "long" | "short"; orders: OrderCalculationResult[]; active_window_levels: number[]; queued_levels: number[]; full_grid_planned_margin: string | number | null; active_window_planned_margin: string | number | null; queued_planned_margin: string | number | null; planned_qty: string | number; planned_average: string | number | null; aggregate_tp_gross_pnl: string | number; aggregate_fee_estimate: string | number | null; aggregate_net_pnl: string | number | null; allocation_limit: string | number; remaining_limit: string | number; utilization_pct: string | number | null; excess: string | number | null; validation_errors: Array<{ level: number; errors: string[] }>; status: "VALID" | "BLOCKED" };
export type CalculationResult = { symbol: string; mark_price: string | number; available_margin: string | number; fee_rate: string | number | null; long: SideCalculationResult; short: SideCalculationResult; combined_planned_margin: string | number; combined_gross_pnl: string | number; combined_fee_estimate: string | number | null; combined_net_pnl: string | number | null; validation_state: "VALID" | "BLOCKED" };
export type AccountApiResponse = Partial<AccountState> & Record<string, unknown>;
export type AuditEvent = { id?: string; created_at: string; entity_type?: string; entity_id?: string; side?: string | null; action: string; before?: Record<string, unknown> | null; after?: Record<string, unknown> | null };
export type RevisionResponse = { id: string; symbol: string; comment: string; validation_state: string; created_at: string };
