import { AccountState } from "./domain";

export type BybitStatusBase = { status?: string; private_integration?: boolean; read_only?: boolean; environment: "mainnet" | "testnet"; credential_source: string; account_state_ready: boolean; orders_ready: boolean; private_state_ready: boolean; last_safe_error?: string | null };
export type HealthResponse = BybitStatusBase;
export type BybitDiagnosticsResponse = BybitStatusBase & { repository_root_found?: boolean; root_env_found?: boolean; module_env_found?: boolean; api_key_present?: boolean; api_secret_present?: boolean; query_api_status?: string; wallet_status?: string; positions_status?: string; open_orders_status?: string };
export type TPCalculationResult = { price: string | number; qty: string | number; close_pct: string | number; gross_pnl: string | number; fee: string | number | null; net_pnl: string | number | null; basis: "planned_entry" | "actual_fill" };
export type OrderCalculationResult = { level: number; planned_entry_price: string | number; configured_qty: string | number; notional: string | number; planned_margin: string | number | null; cumulative_planned_average: string | number | null; planned_tp_qty: string | number; planned_remaining_after_all_tp: string | number; tp_steps: TPCalculationResult[]; validation_errors: string[]; status: "VALID" | "BLOCKED" };
export type SideCalculationResult = { side: "long" | "short"; orders: OrderCalculationResult[]; active_window_levels: number[]; queued_levels: number[]; full_grid_planned_margin: string | number | null; active_window_planned_margin: string | number | null; queued_planned_margin: string | number | null; planned_qty: string | number; planned_average: string | number | null; aggregate_tp_gross_pnl: string | number; aggregate_fee_estimate: string | number | null; aggregate_net_pnl: string | number | null; allocation_limit: string | number; remaining_limit: string | number; utilization_pct: string | number | null; excess: string | number | null; validation_errors: Array<{ level: number; errors: string[] }>; status: "VALID" | "BLOCKED" };
export type CalculationResult = { symbol: string; mark_price: string | number; available_margin: string | number; fee_rate: string | number | null; position_mode?: "HEDGE" | "ONE_WAY" | "UNKNOWN"; position_mode_symbol?: string; enabled_long?: boolean; enabled_short?: boolean; long: SideCalculationResult; short: SideCalculationResult; combined_planned_margin: string | number; combined_gross_pnl: string | number; combined_fee_estimate: string | number | null; combined_net_pnl: string | number | null; validation_state: "VALID" | "BLOCKED"; validation_errors?: Array<{ level: number; errors: string[] }> };
export type AccountApiResponse = { source?: string; stale?: boolean; error?: string; position_mode?: "HEDGE" | "ONE_WAY" | "UNKNOWN"; position_mode_symbol?: string | null; mark_price?: unknown; available_margin?: unknown; equity?: unknown; wallet_balance?: unknown; initial_margin?: unknown; maintenance_margin?: unknown; gross_exposure?: unknown; net_exposure?: unknown; long?: Record<string, unknown> | null; short?: Record<string, unknown> | null; orders?: Array<Record<string, unknown>>; orders_available?: boolean; orders_error?: string | null; updated_at?: string | null; instrument?: { symbol?: string; tick_size?: unknown; qty_step?: unknown; min_order_qty?: unknown; min_notional_value?: unknown } | null };
export type AuditPayload = Record<string, unknown> | unknown[] | null;
export type AuditEvent = { id?: string; created_at: string; entity_type?: string; entity_id?: string; side?: string | null; action: string; before?: AuditPayload; after?: AuditPayload };
export type HistoryItem = { time: string; action: string; side?: string; entityType?: string; entityId?: string; comment?: string; before?: AuditPayload; after?: AuditPayload };
export type RevisionResponse = { id: string; symbol: string; comment: string; validation_state: string; created_at: string };
export type SymbolsResponse = { symbols: string[]; updated_at?: string };
