import { Check, X } from "lucide-react";
import { AccountState, Allocation } from "../domain";
import { money, pct } from "../format";

export function AllocationPanel({ account, allocation, limits, onChange }: { account: AccountState; allocation: Allocation; limits: { long: number | null; short: number | null; reserve: number | null }; onChange: (key: keyof Allocation, value: string) => void }) {
  const complete = allocation.longPct != null && allocation.shortPct != null && allocation.reservePct != null;
  const Box = ({ title, color, value, limit, reserve }: { title: string; color: string; value: number | null; limit: number | null; reserve?: boolean }) => <div className="allocation-box"><div className="alloc-head"><span className={`dot ${color}`}></span><b>{title}</b><label><input type="number" value={value ?? ""} onChange={(event) => onChange(title === "Лонг" ? "longPct" : title === "Шорт" ? "shortPct" : "reservePct", event.target.value)}/> %</label></div><div className="alloc-foot"><span>{reserve ? "Резерв маржи" : "Лимит"}</span><strong>{reserve ? <>{pct(value)}{limits.reserve != null && <small> · {money(limits.reserve)}</small>}</> : money(limit)}</strong></div></div>;
  return <section className="allocation-panel"><div className="section-title"><div><span className="overline">КАПИТАЛ</span><h2>Распределение доступной маржи</h2></div><span className="allocation-total">{complete && allocation.longPct! + allocation.shortPct! + allocation.reservePct! === 100 ? <><Check size={14}/> 100% распределено</> : <><X size={14}/> Укажите 100%</>}</span></div><div className="allocation-grid"><Box title="Лонг" color="green" value={allocation.longPct} limit={limits.long}/><Box title="Шорт" color="red" value={allocation.shortPct} limit={limits.short}/><Box title="Резерв" color="amber" value={allocation.reservePct} limit={limits.reserve} reserve/></div></section>;
}
