import { ShieldCheck, X } from "lucide-react";
import { AccountState, GridOrder } from "../domain";
import { CalculationResult } from "../types";
import { money, price, qty } from "../format";
import { PriceLadder } from "./PriceLadder";

function PositionFacts({ label, position }: { label: string; position: AccountState["longPosition"] }) { return <div><span>Фактический {label}</span><b>{position?.size == null ? "нет данных" : `${qty(position.size)} · ${price(position.avgEntryPrice)}`}</b><small>uPnL: {money(position?.unrealizedPnl)} · плечо: {position?.leverage == null ? "нет данных" : `${position.leverage}x`}</small></div>; }

export function CenterPanel({ account, long, short, tickSize, calculation, blocked }: { account: AccountState; long: GridOrder[]; short: GridOrder[]; tickSize: number | null; calculation?: CalculationResult | null; blocked: boolean }) {
  const longAverage = calculation?.long.planned_average == null ? null : Number(calculation.long.planned_average);
  const shortAverage = calculation?.short.planned_average == null ? null : Number(calculation.short.planned_average);
  const plannedMargin = calculation?.combined_planned_margin == null ? null : Number(calculation.combined_planned_margin);
  const gross = calculation?.combined_gross_pnl == null ? null : Number(calculation.combined_gross_pnl);
  const net = calculation?.combined_net_pnl == null ? null : Number(calculation.combined_net_pnl);
  const fee = calculation?.combined_fee_estimate == null ? null : Number(calculation.combined_fee_estimate);
  return <section className="center-panel"><div className="center-heading"><span className="overline">ОБЩИЙ РАСЧЁТ</span><h2>План сетки</h2><small>{calculation ? "Расчёт подтверждён backend" : "Ожидается подтверждённый расчёт backend"}</small></div><div className="position-box"><div className="position-head"><span>Фактические позиции</span><span className="demo-tag">Наблюдение</span></div><div className="position-values"><PositionFacts label="Лонг" position={account.longPosition}/><PositionFacts label="Шорт" position={account.shortPosition}/><div><span>Mark Price</span><b>{price(account.markPrice)}</b><small>gross: {money(account.grossExposure)} · net: {money(account.netExposure)}</small></div></div></div><div className="position-values"><div><span>Плановая Лонг</span><b>{calculation ? qty(Number(calculation.long.planned_qty)) : "—"} · {calculation ? price(longAverage) : "—"}</b><small>маржа: {calculation ? money(Number(calculation.long.full_grid_planned_margin)) : "—"}</small></div><div><span>Плановая Шорт</span><b>{calculation ? qty(Number(calculation.short.planned_qty)) : "—"} · {calculation ? price(shortAverage) : "—"}</b><small>маржа: {calculation ? money(Number(calculation.short.full_grid_planned_margin)) : "—"}</small></div><div><span>Общий сценарий TP</span><b>{calculation ? money(gross) : "—"} валовой</b><small>fee: {calculation ? (fee == null ? "Комиссия не задана" : money(fee)) : "—"} · net: {calculation ? money(net) : "—"}</small></div></div><PriceLadder account={account} long={long} short={short} tickSize={tickSize} calculation={calculation}/><div className="plan-box"><div><span>Полная плановая маржа</span><b>{calculation ? money(plannedMargin) : "—"}</b></div><div><span>Long gross P&L</span><b>{calculation ? money(Number(calculation.long.aggregate_tp_gross_pnl)) : "—"}</b></div><div><span>Short gross P&L</span><b>{calculation ? money(Number(calculation.short.aggregate_tp_gross_pnl)) : "—"}</b></div></div><div className={`guard ${blocked ? "blocked" : "ok"}`}>{blocked ? <X size={16}/> : <ShieldCheck size={16}/>}<div><b>{blocked ? "Подготовка заблокирована" : "Конфигурация допустима"}</b><small>{blocked ? "Проверьте ошибки рядом с уровнями и лимитами" : "Сетка не превышает выделенный лимит"}</small></div></div></section>;
}
