import { useState } from "react";
import { ApiError, fetchJson } from "../api";
import { AccountState } from "../domain";
import { GeneratedSideConfig, ShadowProposal } from "../shadowTypes";

function Field({ label, value, step = "0.1", onChange }: { label: string; value: number; step?: string; onChange: (value: number) => void }) {
  return <label className="generated-field"><span>{label}</span><input inputMode="decimal" type="number" min="0" step={step} value={value} onChange={(event) => onChange(Number(event.target.value))}/></label>;
}

function sidePayload(config: GeneratedSideConfig) {
  return { enabled: config.enabled, order_count: config.orderCount, grid_depth_pct: config.gridDepthPct, first_order_offset_pct: config.firstOrderOffsetPct, distribution_coefficient: config.distributionCoefficient, leverage: config.leverage, martingale_coefficient: config.martingaleCoefficient, sizing_mode: config.sizingMode, allocation_pct: config.allocationPct, active_order_count: config.activeOrderCount, tp_steps: config.tpSteps.map((step) => ({ move_pct: step.movePct, close_pct: step.closePct })), trailing_enabled: config.trailingEnabled, trailing_offset_pct: config.trailingOffsetPct, opposite_upnl_reinvestment_pct: config.oppositeUpnlReinvestmentPct, manual_overrides: config.manualOverrides };
}

export function GeneratedGridPanel({ account, allocation, long, short, onLongChange, onShortChange }: { account: AccountState; allocation: { longPct: number | null; shortPct: number | null; reservePct: number | null }; long: GeneratedSideConfig; short: GeneratedSideConfig; onLongChange: (config: GeneratedSideConfig) => void; onShortChange: (config: GeneratedSideConfig) => void }) {
  const [proposal, setProposal] = useState<ShadowProposal | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const update = (side: "long" | "short", key: keyof GeneratedSideConfig, value: number | boolean) => (side === "long" ? onLongChange : onShortChange)({ ...(side === "long" ? long : short), [key]: value });
  const generate = async () => {
    setLoading(true); setError("");
    try { setProposal(await fetchJson<ShadowProposal>("/api/shadow/generate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol: account.symbol, allocation: { long_pct: allocation.longPct ?? long.allocationPct, short_pct: allocation.shortPct ?? short.allocationPct, reserve_pct: allocation.reservePct ?? Math.max(0, 100 - long.allocationPct - short.allocationPct) }, long: sidePayload(long), short: sidePayload(short) }) })); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Shadow расчёт недоступен"); }
    setLoading(false);
  };
  const SideEditor = ({ side, config }: { side: "long" | "short"; config: GeneratedSideConfig }) => <div className={`generated-side ${side}`}><div className="generated-side-head"><b>{side === "long" ? "LONG" : "SHORT"} GENERATED GRID</b><button type="button" className={config.enabled ? "selected" : ""} onClick={() => update(side, "enabled", !config.enabled)}>{config.enabled ? "ON" : "OFF"}</button></div><div className="generated-fields"><Field label="Уровней" step="1" value={config.orderCount} onChange={(value) => update(side, "orderCount", Math.max(1, Math.floor(value)))}/><Field label="Глубина, %" value={config.gridDepthPct} onChange={(value) => update(side, "gridDepthPct", value)}/><Field label="Первый offset, %" value={config.firstOrderOffsetPct} onChange={(value) => update(side, "firstOrderOffsetPct", value)}/><Field label="Distribution" value={config.distributionCoefficient} onChange={(value) => update(side, "distributionCoefficient", value)}/><Field label="Leverage" value={config.leverage} onChange={(value) => update(side, "leverage", value)}/><Field label="Martingale" value={config.martingaleCoefficient} onChange={(value) => update(side, "martingaleCoefficient", value)}/><Field label="Active window" step="1" value={config.activeOrderCount} onChange={(value) => update(side, "activeOrderCount", Math.max(1, Math.floor(value)))}/><Field label="Allocation, %" value={config.allocationPct} onChange={(value) => update(side, "allocationPct", value)}/></div><div className="experimental-line"><label><input type="checkbox" checked={config.trailingEnabled} onChange={(event) => update(side, "trailingEnabled", event.target.checked)}/> Trailing <small>EXPERIMENTAL</small></label><label><input type="checkbox" checked={config.oppositeUpnlReinvestmentPct > 0} onChange={(event) => update(side, "oppositeUpnlReinvestmentPct", event.target.checked ? 10 : 0)}/> Opposite uPnL <small>EXPERIMENTAL</small></label></div></div>;
  return <section className="generated-panel"><div className="generated-heading"><div><span className="overline">SHADOW / SIMULATION</span><h2>Generated Grid</h2><p>Виртуальные ордера · Bybit write actions отключены</p></div><button className="save" type="button" onClick={() => void generate()} disabled={loading || account.markPrice == null}>{loading ? "Считаю…" : "Построить preview"}</button></div><div className="generated-grid"><SideEditor side="long" config={long}/><SideEditor side="short" config={short}/></div>{error && <p className="strategy-sides-warning">{error}</p>}{proposal && <div className="shadow-result"><div><b>VIRTUAL · {proposal.symbol}</b><span>Capital base: {proposal.capital_snapshot.capital_base ?? "нет данных"}</span><span>Validation: {proposal.validation.state}</span></div><div className="shadow-sides">{["long", "short"].map((side) => <div key={side}><b>{side.toUpperCase()}</b><span>{proposal.sides[side]?.status} · {proposal.sides[side]?.orders.length ?? 0} уровней</span><small>{proposal.sides[side]?.orders.slice(0, 3).map((order) => `#${order.level} ${order.entry_price} · ${order.qty}`).join(" | ")}</small></div>)}</div><small>Ордер не отправлен на Bybit</small></div>}</section>;
}
